### ISSUE TITLE
ABI Encoder v2 Nested Structs

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#19]
**Is your feature request related to a problem? Please describe.**

ABI Encoder v2 support to `abigen` was introduced in https://github.com/gakonst/ethers-rs/pull/17. It only works if there's no nesting. If there's a nested struct, e.g. 

```solidity
contract UserDirectory {
    struct Contact {
        string email;
        string phone;
    }
    struct User {
        string name;
        address addr;
        Contact contact;
    }
}
```

...then a generated function which uses `User` would be something like: `fn add_user(&self, user: (String, Address, (String, String)))`. The tuple unfortunately does not implement `Tokenize` or `Detokenize`.

**Describe the solution you'd like**

We need to find a way to implement Tokenize/Detokenize for nested structs. Maybe a more elaborate macro implementation?

**Describe alternatives you've considered**

Ideally we should get these done with generics, but doesn't seem possible?

**Comment by gakonst** [comment]
TheGraph has also bumped in the same problem: https://github.com/graphprotocol/solidity-bindgen/pull/5/files#diff-161f437210fcf6e05c4deb47640febb3R127-R145

**Comment by gakonst** [comment]
Closed in https://github.com/gakonst/ethers-rs/pull/42
