### ISSUE TITLE
Can't build from git

### ISSUE THREAD

**Issue by kayabaNerve** [gakonst/ethers-rs#1470]
**Version**
ethers-rs commit 8db1899820f0608a0acee1ca428b257fcffac067
rustc 1.62.0 (a8314ef7d 2022-06-27)

**Platform**
Linux _ 5.18.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 30 May 2022 17:53:11 +0000 x86_64 GNU/Linux

**Description**
git fails to build, I believe due to #1465.

```
error[E0277]: the trait bound `k256::ecdsa::SigningKey: DigestSigner<D, _>` is not satisfied
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/coins-bip32-0.7.0/src/macros.rs:16:28
   |
16 |                 self.$attr.try_sign_digest(digest)
   |                            ^^^^^^^^^^^^^^^ the trait `DigestSigner<D, _>` is not implemented for `k256::ecdsa::SigningKey`
   |
  ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/coins-bip32-0.7.0/src/xkeys.rs:87:1
   |
87 | inherit_signer!(XPriv.key);
   | -------------------------- in this macro invocation
   |
   = help: the following other types implement trait `DigestSigner<D, S>`:
             <k256::ecdsa::SigningKey as DigestSigner<D, ecdsa::Signature<Secp256k1>>>
             <k256::ecdsa::SigningKey as DigestSigner<D, k256::ecdsa::recoverable::Signature>>
   = note: this error originates in the macro `inherit_signer` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `k256::ecdsa::SigningKey: DigestSigner<D, _>` is not satisfied
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/coins-bip32-0.7.0/src/macros.rs:34:28
   |
34 |                 self.$attr.try_sign_digest(digest)
   |                            ^^^^^^^^^^^^^^^ the trait `DigestSigner<D, _>` is not implemented for `k256::ecdsa::SigningKey`
   |
  ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/coins-bip32-0.7.0/src/xkeys.rs:87:1
   |
87 | inherit_signer!(XPriv.key);
   | -------------------------- in this macro invocation
   |
   = help: the following other types implement trait `DigestSigner<D, S>`:
             <k256::ecdsa::SigningKey as DigestSigner<D, ecdsa::Signature<Secp256k1>>>
             <k256::ecdsa::SigningKey as DigestSigner<D, k256::ecdsa::recoverable::Signature>>
   = note: this error originates in the macro `inherit_signer` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `coins-bip32` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

I can, however, build coins-bip32 from git (version 0.7 with k256 0.11), so I'm unsure why this is happening. I'm sorry if this is an issue for coins-bip32 instead.

**Comment by gakonst** [comment]
Just made a fresh repo and it worked. Try running `cargo update`? (Closing)

**Comment by kayabaNerve** [comment]
I did try this from a fresh repo. I was sent this to try to help someone out, and have never touched ethers before. Weird that its on some systems yet not others...
